#!/bin/bash

mkdir build
wget -O build/OpenJDK11U-jdk_x64_linux_hotspot_11.0.10_9.tar.gz https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.10_9.tar.gz
tar -xf build/OpenJDK11U-jdk_x64_linux_hotspot_11.0.10_9.tar.gz -C build/
rm build/OpenJDK11U-jdk_x64_linux_hotspot_11.0.10_9.tar.gz